media:
  input: public/assets
  output: /assets
  categories: ["image"]
content:
  - name: components
    label: Components
    type: collection
    format: "json"
    subfolders: false
    path: components
    filename: "{fields.slug}.json"
    view:
      fields: [title, date, status]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - name: status
        label: Status
        type: select
        options:
          multiple: true
          values:
          - value: alpha
            label: Alpha
          - value: beta
            label: Beta
          - value: deprecated
            label: Deprecated
          - value: wip
            label: WIP
      - { name: summary, label: Summary, type: string }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ Form, Buttons ]
      - name: category
        label: Category
        type: select
        options:
          multiple: true
          values: [ Components, Elements ]
      - name: platform
        label: Platform
        type: object
        fields:
          - name: web
            label: Web
            type: boolean
            default: false
          - name: ios
            label: iOS
            type: boolean
            default: false
          - name: android
            label: Android
            type: boolean
            default: false
      - name: overview
        label: Overview
        type: object
        list: true
        fields:
          - name: section
            label: Section
            type: object
            fields: 
             - { name: title, label: Title, type: string }
             - { name: description, label: Description, type: rich-text }
             - name: image
               label: Image
               type: object
               fields: 
                - { name: id, label: ID, type: string }
                - { name: caption, label: Caption, type: string }
      - name: ux-text
        label: UX text
        type: object
        fields:
          - name: section
            label: Section
            type: object
            list: true
            fields: 
             - { name: title, label: Title, type: string }
             - { name: description, label: Description, type: rich-text }
             - name: image
               label: Image
               type: object
               fields: 
                - { name: id, label: ID, type: string }
                - { name: caption, label: Caption, type: string }
      - name: accessibility
        label: Accessibility
        type: object
        fields:
          - name: section
            label: Section
            type: object
            list: true
            fields: 
             - { name: title, label: Title, type: string }
             - { name: description, label: Description, type: rich-text }
             - name: image
               label: Image
               type: object
               fields: 
                - { name: id, label: ID, type: string }
                - { name: caption, label: Caption, type: string }
          
  - name: pages
    label: Pages
    type: collection
    format: "json"
    path: _pages
    filename: "{fields.slug}.json"
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: related_components
        label: Related Components
        type: reference
        options:
          collection: components
          multiple: true
          search: "title"
          value: "{title}"
          label: "{title}"
      - { name: body, label: Body, type: rich-text }

  - name: templates
    label: Templates
    type: collection
    format: "json"
    path: templates
    filename: "{fields.slug}.json"
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - name: code
        label: Code
        type: code
        options:
          language: html
      - name: related_components
        label: Related Components
        type: reference
        options:
         collection: components
         multiple: true
         search: "title"
         value: "{title}"
         label: "{title}"
