media:
  input: public/assets
  output: /assets
  categories: ["image"]
content:
  - name: components
    label: Components
    type: collection
    format: "json"
    subfolders: false
    path: content/components
    filename: "{fields.slug}.json"
    view:
      fields: [title, date, status]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - name: beta
        label: Beta
        type: boolean
        default: false
      - { name: summary, label: Summary, type: string }
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [Form, Buttons]
      - name: category
        label: Category
        type: select
        options:
          multiple: true
          values: [Components, Elements]
      - name: platform
        label: Platform
        type: object
        fields:
          - name: web
            label: Web
            type: boolean
            default: false
          - name: ios
            label: iOS
            type: boolean
            default: false
          - name: android
            label: Android
            type: boolean
            default: false
      - name: overview
        type: object
        label: Overview
        list: true
        fields:
          - name: column
            type: object
            label: Column
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - name: column_title_tag
                label: Tag
                type: select
                required: false
                options:
                  default: H2
                  values: [H1, H2, H3, H4, H5]
              - { name: description, label: Description, type: rich-text }
              - name: image
                label: Image
                type: object
                fields:
                  - { name: id, label: ID, type: string }
                  - { name: caption, label: Caption, type: string }

      - name: ux-text
        label: UX text
        type: object
        fields:
          - name: section
            label: Section
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: rich-text }
              - name: image
                label: Image
                type: object
                fields:
                  - { name: id, label: ID, type: string }
                  - { name: caption, label: Caption, type: string }
      - name: accessibility
        label: Accessibility
        type: object
        fields:
          - name: section
            label: Section
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: rich-text }
              - name: image
                label: Image
                type: object
                fields:
                  - { name: id, label: ID, type: string }
                  - { name: caption, label: Caption, type: string }

  - name: pages
    label: Pages
    type: collection
    format: "json"
    path: content/pages
    filename: "{fields.slug}.json"
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - { name: body, label: Body, type: rich-text }

  - name: navigation
    label: Navigation
    type: collection
    format: "json"
    path: content/navigation
    view:
      fields: [title]
    filename: "{fields.slug}.json"
    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - name: links
        label: Links
        type: object
        list: true
        fields:
          - { name: title, label: Title, type: string }
          - { name: slug, label: Slug, type: string }
          - { name: icon, label: Icon, type: string }

  - name: templates
    label: Templates
    type: collection
    format: "json"
    path: content/templates
    filename: "{fields.slug}.json"
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - name: code
        label: Code
        type: code
        options:
          language: html
      - name: related_components
        label: Related Components
        type: reference
        options:
          collection: components
          multiple: true
          search: "title"
          value: "{title}"
          label: "{title}"
  - name: snippets
    label: Snippets
    type: collection
    format: "json"
    path: content/snippets
    filename: "{fields.slug}.json"
    view:
      fields: [title, id]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: id, label: ID, type: string, required: true }
      - name: snippet_component
        label: Component
        type: reference
        options:
          collection: components
          multiple: false
          search: "title"
          value: "{title}"
          label: "{title}"
      - name: code
        label: Code
        type: code
        options:
          language: html
  - name: home
    label: Home
    type: file
    format: "json"
    path: content/home.json
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: summary, label: Summary, type: rich-text }
