# .github/workflows/deploy-pages.yml
name: 🚀 Deploy Pages

on:
  workflow_dispatch: {}
  push:
    paths:
      - "content/**"
      - "data/**"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Process content files
        run: node scripts/content.script.js

      - name: Verify Content Structure
        run: |
          echo "Content structure:"
          tree data || true
          echo "\nFiles in data directory:"
          find data -type f -ls

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare upload
        run: |
          echo "Preparing files for upload..."
          cd data
          find . -type f > files.txt
          echo "Files to be uploaded:"
          cat files.txt
          tar czf ../artifact.tar.gz .
          cd ..

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: data

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print deployment summary
        run: |
          echo "✅ Deployment completed!"
          echo "📚 Content is available at:"
          echo "- GitHub Pages: ${{ steps.deployment.outputs.page_url }}"
          echo "\nDeployed files:"
          find data -type f | while read -r file; do
            echo "- ${{ steps.deployment.outputs.page_url }}${file#data/}"
          done
