# .github/workflows/generate-images.yml
name: Generate Images

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          npm install axios ajv

      - name: Run Image Generation Script
        env:
          FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
          FIGMA_ACCESS_KEY: ${{ secrets.FIGMA_ACCESS_KEY }}
        run: node scripts/images.script.js

      - name: Debug - List generated content
        run: |
          echo "Contents of data/components directory:"
          ls -la data/components/

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add "data/components/**/*.images.json"
          git commit -m "Update component images" || echo "No changes to commit"
          git push
