# .github/workflows/generate-og.yml
name: 🎨 Generate OG Images

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            libpixman-1-dev

      - name: Install dependencies
        run: |
          npm install canvas@2.11.2

      - name: Generate OG images
        run: node scripts/og.script.js

      - name: Verify Generated Files
        run: |
          echo "Checking generated OG images..."
          find data -name "*.og.png" -type f

          echo "\nChecking updated index files..."
          cat data/components/components.json
          cat data/pages/pages.json
          cat data/snippets/snippets.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: data

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Commit changes to main branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Stage all changes in data directory
          git add data/

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update OG images and index files"
            git push origin main
          fi

      - name: Print Summary
        run: |
          echo "✅ Deployment completed!"
          echo "\n📊 Generated OG images:"
          find data -name "*.og.png" -type f | while read -r file; do
            echo "- https://api.seb.io/${file#data/}"
          done
