name: Generate Images

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Create package.json if not exists
        run: |
          if [ ! -f package.json ]; then
            echo '{"name":"image-generator","version":"1.0.0","private":true}' > package.json
          fi

      - name: Install Dependencies
        run: |
          npm install axios
          npm install ajv

      - name: Run Image Generation Script
        env:
          FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
          FIGMA_ACCESS_KEY: ${{ secrets.FIGMA_ACCESS_KEY }}
        run: node scripts/images.script.js

      - name: Debug - List generated content
        run: |
          echo "Contents of generated directory:"
          ls -la generated/

      - name: Create index.html
        run: |
          echo "<html><body><h1>Generated Files</h1><ul>" > generated/index.html
          find generated -type f -name "*.json" | while read file; do
            filename=$(basename "$file")
            dirname=$(dirname "$file" | sed 's|generated/||')
            echo "<li><a href='$dirname/$filename'>$dirname/$filename</a></li>" >> generated/index.html
          done
          echo "</ul></body></html>" >> generated/index.html

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/
          git commit -m "Update generated component images" || echo "No changes to commit"
          git push
