# .github/workflows/generate-og.yml
name: 🎨 Generate OG Images

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            libpixman-1-dev

      - name: Install dependencies
        run: |
          npm install canvas@2.11.2

      - name: Process content
        run: node scripts/content.script.js

      - name: Generate OG images
        run: |
          node scripts/og.script.js

          echo "\nVerifying generated files..."
          echo "Data directory structure:"
          tree data || true

          echo "\nFound OG images:"
          find data -name "*.og.png" -type f -ls

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          echo "Changes to be committed:"
          git add -A
          git status

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add OG images and update indexes"
            git push origin main
          fi

      - name: Print Summary
        run: |
          echo "Generation Summary:"
          cat og-generation-summary.json

          echo "\nGenerated OG images are at:"
          find data -name "*.og.png" -type f | while read -r file; do
            echo "- $file"
          done
