name: Generate Images

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Dependencies
        run: npm install axios ajv

      - name: Run Image Generation Script
        env:
          FIGMA_PROJECT_ID: ${{ secrets.FIGMA_PROJECT_ID }}
          FIGMA_ACCESS_KEY: ${{ secrets.FIGMA_ACCESS_KEY }}
        run: node scripts/images.script.js

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-images
          path: generated/
          if-no-files-found: error

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-images
          path: .

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated component images [skip ci]" || echo "No changes to commit"
          git push
